# Generated by Django 5.1.4 on 2025-02-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
