# Generated by Django 5.1.3 on 2024-12-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_serie_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
