# Generated by Django 5.1.3 on 2024-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='fecha_lanzamiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
