# Generated by Django 5.1.4 on 2025-03-06 13:41

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='generos',
            field=models.ManyToManyField(blank=True, through='Series.SerieGenero', to='Series.generos'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Series/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='plataformas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('flow', 'Flow'), ('disney_plus', 'Disney Plus'), ('max', 'Max'), ('amazon_prime', 'Amazon Prime'), ('paramount', 'Paramount'), ('apple_tv', 'Apple TV'), ('netflix', 'Netflix')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='reparto',
            field=models.CharField(blank=True, default='Desconocido', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='temporada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
