# Generated by Django 5.1.4 on 2025-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_genero_remove_serie_genero_serie_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='serie',
            name='genero',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
