# Generated by Django 5.1.3 on 2024-12-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_alter_serie_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='reparto',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
