# Generated by Django 5.1.4 on 2025-01-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0003_remove_serie_genero_delete_genero_serie_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Terror', 'Terror'), ('Aventura', 'Aventura')], default='Desconocido', max_length=100),
        ),
    ]
