# Generated by Django 5.1.4 on 2025-01-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0005_alter_serie_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.CharField(max_length=200),
        ),
    ]
