# Generated by Django 5.1.4 on 2025-01-06 16:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0008_serieguardada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('comedia', 'Comedia'), ('drama', 'Drama'), ('accion', 'Acción'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia Ficción'), ('romance', 'Romance'), ('documental', 'Documental'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('aventura', 'Aventura'), ('Política', 'política')], max_length=98),
        ),
    ]
