# Generated by Django 5.1.4 on 2025-02-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0015_opinion_serie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opinion_serie',
            unique_together=set(),
        ),
    ]
