# Generated by Django 5.1.4 on 2025-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0016_alter_opinion_serie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion_serie',
            name='estrellas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
