# Generated by Django 5.1.4 on 2025-02-10 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0018_alter_opinion_serie_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion_serie',
            name='estrellas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
