# Generated by Django 5.1.4 on 2025-02-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0019_alter_opinion_serie_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion_serie',
            name='estrellas',
            field=models.IntegerField(),
        ),
    ]
